# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: 'Verify Package Version'
description: '🙏 Verify your package version whether meets some conditions.'
author: 'xrkffgg'

branding:
  # https://feathericons.com/
  # e.g. https://haya14busa.github.io/github-action-brandings/
  icon: 'box'
  color: 'green'

inputs:
  token:
    description: Secret GitHub API token to use for making API requests.
    default: ${{ github.token }}
    required: true
  title-include-content:
    description: Verify that the title contains content
  title-include-version:
    description: Verify that the title whether contains version
  open-comment:
    description: Whether to open comments

runs:
  using: 'node12'
  main: 'dist/index.js'
